name: Deploy to S3

on:
  push:
    branches:
      - main  # կամ քո հիմնական բրանչի անունը

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --acl public-read --exclude ".git/*" --exclude ".github/*"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'  # փոխիր ըստ քո բաքեթի ռեգիոնի
          SOURCE_DIR: 'dist'       # փոխիր ըստ build-ի output-ի (օրինակ՝ 'build' կամ 'out')






