name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: my-epamlearn
        AWS_ACCESS_KEY_ID: ${{ AKIARVP4W5OK6OFAUHDV }}
        AWS_SECRET_ACCESS_KEY: ${{ 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 }}
        AWS_REGION: us-east-1
        SOURCE_DIR: ./
